import type { PresetSchema } from '../types/preset';

/**
 * Factory presets featuring the newly reconstructed Category 1: Compressors
 */
export const FACTORY_PRESETS: PresetSchema[] = [
  {
    version: 1,
    id: 'preset-nashville-dynacomp',
    name: 'Nashville Chicken Pickin',
    category: 'factory',
    description: 'Percussive, clicky attack and squashed funk/country leveling with the MXR Dyna Comp',
    inputGain: 1.0,
    masterVolume: 0.8,
    cabinet: {
      enabled: true,
      model: '2x12-open',
      mic: 'sm57',
      position: 0.75,
      mix: 0.8,
    },
    pedals: [
      {
        id: 'pedal-dynacomp-init',
        type: 'comp-dynacomp',
        name: 'MXR Dyna Comp',
        enabled: true,
        parameters: {
          output: 5.5,
          sensitivity: 6.8,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-studio-keeley',
    name: 'Studio Audiophile Clean',
    category: 'factory',
    description: 'Transparent audiophile studio leveling and sweet sustain with the Keeley 4-Knob C4',
    inputGain: 1.0,
    masterVolume: 0.8,
    cabinet: {
      enabled: true,
      model: '1x12-open',
      mic: 'condenser',
      position: 0.6,
      mix: 0.85,
    },
    pedals: [
      {
        id: 'pedal-keeley-init',
        type: 'comp-keeley',
        name: 'Keeley Compressor',
        enabled: true,
        parameters: {
          sustain: 5.0,
          level: 5.2,
          attack: 6.0,
          clipping: 7.0,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-singing-ross',
    name: 'Singing Jam Sustain',
    category: 'factory',
    description: 'Warm organic soft-knee singing sustain with the vintage grey Ross Compressor',
    inputGain: 1.0,
    masterVolume: 0.8,
    cabinet: {
      enabled: true,
      model: '4x12-closed',
      mic: 'ribbon',
      position: 0.5,
      mix: 0.8,
    },
    pedals: [
      {
        id: 'pedal-ross-init',
        type: 'comp-ross',
        name: 'Ross Compressor',
        enabled: true,
        parameters: {
          sustain: 6.5,
          level: 5.0,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-boss-cs3-punch',
    name: 'Dynamic Punch & Snap',
    category: 'factory',
    description: 'Articulate pick attack and presence bite with the Boss CS-3 Compression Sustainer',
    inputGain: 1.0,
    masterVolume: 0.8,
    cabinet: {
      enabled: true,
      model: '2x12-closed',
      mic: 'md421',
      position: 0.7,
      mix: 0.8,
    },
    pedals: [
      {
        id: 'pedal-cs3-init',
        type: 'comp-cs3',
        name: 'Boss CS-3',
        enabled: true,
        parameters: {
          level: 5.2,
          tone: 5.8,
          attack: 5.0,
          sustain: 5.5,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-srv-ts808',
    name: 'Texas Blues Strat (TS-808)',
    category: 'factory',
    description: 'Iconic Stevie Ray Vaughan mid-hump vocal overdrive with Tube Screamer TS-808 pushing an open cab',
    inputGain: 1.0,
    masterVolume: 0.85,
    cabinet: {
      enabled: true,
      model: '2x12-open',
      mic: 'sm57',
      position: 0.8,
      mix: 0.85,
    },
    pedals: [
      {
        id: 'pedal-ts808-srv',
        type: 'od-ts808',
        name: 'Tube Screamer TS-808',
        enabled: true,
        parameters: {
          overdrive: 6.2,
          tone: 5.5,
          level: 7.0,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-classic-sd1',
    name: 'Classic Rock Asym Crunch (SD-1)',
    category: 'factory',
    description: 'Rich 2nd-harmonic tube bite from the Boss SD-1 asymmetrical clipping into a 4x12 stack',
    inputGain: 1.0,
    masterVolume: 0.85,
    cabinet: {
      enabled: true,
      model: '4x12-closed',
      mic: 'sm57',
      position: 0.7,
      mix: 0.85,
    },
    pedals: [
      {
        id: 'pedal-sd1-crunch',
        type: 'od-sd1',
        name: 'Boss SD-1',
        enabled: true,
        parameters: {
          level: 6.5,
          tone: 5.2,
          drive: 6.0,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-klon-golden',
    name: 'Mythical Golden Boost (Klon)',
    category: 'factory',
    description: 'Transparent 18V headroom boost with singing germanium diode saturation from the Klon Centaur',
    inputGain: 1.0,
    masterVolume: 0.85,
    cabinet: {
      enabled: true,
      model: '2x12-open',
      mic: 'condenser',
      position: 0.65,
      mix: 0.8,
    },
    pedals: [
      {
        id: 'pedal-klon-gold',
        type: 'od-klon',
        name: 'Klon Centaur',
        enabled: true,
        parameters: {
          gain: 4.8,
          treble: 5.4,
          output: 6.8,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-bd2-tweed',
    name: 'Tweed Touch Sensitivity (BD-2)',
    category: 'factory',
    description: 'Dynamic multi-stage FET response from subtle breakup to gritty vintage rasp with the Blues Driver',
    inputGain: 1.0,
    masterVolume: 0.85,
    cabinet: {
      enabled: true,
      model: '1x12-open',
      mic: 'ribbon',
      position: 0.55,
      mix: 0.85,
    },
    pedals: [
      {
        id: 'pedal-bd2-tweed',
        type: 'od-bd2',
        name: 'Boss BD-2',
        enabled: true,
        parameters: {
          level: 6.0,
          tone: 5.0,
          gain: 5.8,
        },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-ocd-marshall',
    name: 'British Roar HP (Fulltone OCD)',
    category: 'factory',
    description: 'Cranked British stack power sag and harmonic bloom with the Fulltone OCD High Peak mode',
    inputGain: 1.0,
    masterVolume: 0.85,
    cabinet: {
      enabled: true,
      model: '4x12-closed',
      mic: 'md421',
      position: 0.75,
      mix: 0.85,
    },
    pedals: [
      {
        id: 'pedal-ocd-hp',
        type: 'od-ocd',
        name: 'Fulltone OCD',
        enabled: true,
        parameters: {
          volume: 6.2,
          tone: 5.6,
          drive: 6.5,
          mode: 1,
        },
      },
    ],
  },
];
