import type { PresetSchema } from '../types/preset';

export const FACTORY_PRESETS: PresetSchema[] = [
  {
    version: 1,
    id: 'preset-classic-rock',
    name: 'Classic British Rock & Crunch',
    category: 'factory',
    description: 'Vintage 70s British tube crunch and soaring lead tone with tube overdrive, British stack, warm tape delay, and studio plate reverb.',
    pedals: [
      {
        id: 'classic-boost',
        type: 'gain',
        name: 'BOOSTER PRO',
        enabled: true,
        parameters: { boost: 6, level: 0 },
      },
      {
        id: 'classic-od',
        type: 'overdrive',
        name: 'TUBE SCREAMER',
        enabled: true,
        parameters: { drive: 14, tone: 3200, level: 1 },
      },
      {
        id: 'classic-amp',
        type: 'amp',
        name: 'LEGEND 100',
        enabled: true,
        parameters: { gain: 11, bass: 2, middle: 3, treble: 3, presence: 2, master: 0 },
      },
      {
        id: 'classic-cab',
        type: 'cab',
        name: 'CABINET 4X12',
        enabled: true,
        parameters: { model: 0, mic: 0.2, level: 0 },
      },
      {
        id: 'classic-delay',
        type: 'delay',
        name: 'TAPE ECHO',
        enabled: true,
        parameters: { time: 0.38, feedback: 0.4, tone: 3200, mix: 0.3 },
      },
      {
        id: 'classic-reverb',
        type: 'reverb',
        name: 'CELESTIAL REVERB',
        enabled: true,
        parameters: { decay: 2.4, damp: 4200, mix: 0.25, level: 0 },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-stadium-lead',
    name: 'Stadium Solo Lead',
    category: 'factory',
    description: 'Screaming 80s arena rock lead with tube overdrive, high gain amp, delay, and lush reverb.',
    pedals: [
      {
        id: 'lead-boost',
        type: 'gain',
        name: 'BOOSTER PRO',
        enabled: true,
        parameters: { boost: 8, level: 0 },
      },
      {
        id: 'lead-od',
        type: 'overdrive',
        name: 'TUBE SCREAMER',
        enabled: true,
        parameters: { drive: 16, tone: 3400, level: 1 },
      },
      {
        id: 'lead-amp',
        type: 'amp',
        name: 'LEGEND 100',
        enabled: true,
        parameters: { gain: 12, bass: 1, middle: 4, treble: 3, presence: 3, master: 0 },
      },
      {
        id: 'lead-cab',
        type: 'cab',
        name: 'CABINET 4X12',
        enabled: true,
        parameters: { model: 0, mic: 0.2, level: 0 },
      },
      {
        id: 'lead-delay',
        type: 'delay',
        name: 'TAPE ECHO',
        enabled: true,
        parameters: { time: 0.42, feedback: 0.45, tone: 3500, mix: 0.35 },
      },
      {
        id: 'lead-reverb',
        type: 'reverb',
        name: 'CELESTIAL REVERB',
        enabled: true,
        parameters: { decay: 2.8, damp: 4200, mix: 0.3, level: 0 },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-clean-ambient',
    name: 'Dreamy Ambient Space',
    category: 'factory',
    description: 'Lush shimmering clean tone with subtle boost, chorus, tape delay, and deep cavernous space.',
    pedals: [
      {
        id: 'ambient-boost',
        type: 'gain',
        name: 'BOOSTER PRO',
        enabled: true,
        parameters: { boost: 4, level: 0 },
      },
      {
        id: 'ambient-eq',
        type: 'eq',
        name: 'TONE SCULPTOR',
        enabled: true,
        parameters: { bass: 2, middle: -1, treble: 4, level: 0 },
      },
      {
        id: 'ambient-chorus',
        type: 'chorus',
        name: 'OCEAN CHORUS',
        enabled: true,
        parameters: { rate: 1.0, depth: 0.0035, mix: 0.6, level: 0 },
      },
      {
        id: 'ambient-delay',
        type: 'delay',
        name: 'TAPE ECHO',
        enabled: true,
        parameters: { time: 0.48, feedback: 0.6, tone: 4000, mix: 0.45 },
      },
      {
        id: 'ambient-reverb',
        type: 'reverb',
        name: 'CELESTIAL REVERB',
        enabled: true,
        parameters: { decay: 4.5, damp: 5000, mix: 0.55, level: 0 },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-desert-fuzz',
    name: 'Desert Fuzz & Phase',
    category: 'factory',
    description: 'Stoner rock thick fuzz wall with swirling 4-stage phaser through an overdriven tube stack.',
    pedals: [
      {
        id: 'fuzz-fuzz',
        type: 'fuzz',
        name: 'PURPLE HAZE',
        enabled: true,
        parameters: { fuzz: 26, tone: 3200, level: 0 },
      },
      {
        id: 'fuzz-phaser',
        type: 'phaser',
        name: 'PHASE 90',
        enabled: true,
        parameters: { speed: 0.6, depth: 850, feedback: 0.4, level: 0 },
      },
      {
        id: 'fuzz-amp',
        type: 'amp',
        name: 'LEGEND 100',
        enabled: true,
        parameters: { gain: 10, bass: 3, middle: 2, treble: 2, presence: 1, master: 0 },
      },
      {
        id: 'fuzz-cab',
        type: 'cab',
        name: 'CABINET 4X12',
        enabled: true,
        parameters: { model: 0, mic: 0.5, level: 0 },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-vintage-surf',
    name: 'Vintage Surf Tremolo',
    category: 'factory',
    description: '60s California surf sound with pulsed optical tremolo and spring-like room reflections.',
    pedals: [
      {
        id: 'surf-od',
        type: 'overdrive',
        name: 'TUBE SCREAMER',
        enabled: true,
        parameters: { drive: 4, tone: 4500, level: 0 },
      },
      {
        id: 'surf-tremolo',
        type: 'tremolo',
        name: 'PULSE TREMOLO',
        enabled: true,
        parameters: { rate: 5.5, depth: 0.75, level: 0 },
      },
      {
        id: 'surf-cab',
        type: 'cab',
        name: 'CABINET 4X12',
        enabled: true,
        parameters: { model: 1, mic: 0.2, level: 0 },
      },
      {
        id: 'surf-reverb',
        type: 'reverb',
        name: 'CELESTIAL REVERB',
        enabled: true,
        parameters: { decay: 2.2, damp: 5500, mix: 0.45, level: 0 },
      },
    ],
  },
  {
    version: 1,
    id: 'preset-direct-bypass',
    name: 'Direct Passthrough',
    category: 'factory',
    description: 'Completely uncolored clean guitar passthrough with transparent studio buffer and flat tone sculpt.',
    pedals: [
      {
        id: 'bypass-boost',
        type: 'gain',
        name: 'BOOSTER PRO',
        enabled: true,
        parameters: { boost: 0, level: 0 },
      },
      {
        id: 'bypass-eq',
        type: 'eq',
        name: 'TONE SCULPTOR',
        enabled: true,
        parameters: { bass: 0, middle: 0, treble: 0, level: 0 },
      },
    ],
  },
];
