import type { AudioPedalNode, PedalMetadata } from '../../types/pedal';
import { GainPedalNode } from './GainPedalNode';
import { OverdrivePedalNode } from './OverdrivePedalNode';
import { DistortionPedalNode } from './DistortionPedalNode';
import { FuzzPedalNode } from './FuzzPedalNode';
import { Eq3BandPedalNode } from './Eq3BandPedalNode';
import { ChorusPedalNode } from './ChorusPedalNode';
import { TremoloPedalNode } from './TremoloPedalNode';
import { PhaserPedalNode } from './PhaserPedalNode';
import { FlangerPedalNode } from './FlangerPedalNode';
import { DelayPedalNode } from './DelayPedalNode';
import { ReverbPedalNode } from './ReverbPedalNode';
import { AmpPedalNode } from './AmpPedalNode';
import { CabPedalNode } from './CabPedalNode';
import { CompressorPedalNode } from './CompressorPedalNode';
import { NoiseGatePedalNode } from './NoiseGatePedalNode';
import { LooperPedalNode } from './LooperPedalNode';

export const PEDAL_DEFINITIONS: Record<string, PedalMetadata> = {
  noiseGate: {
    type: 'noiseGate',
    name: 'SILENCE PRO',
    subtitle: 'Adaptive Studio Noise Gate',
    category: 'utility',
    chassisColor: 'linear-gradient(180deg, #373e4a 0%, #1e2229 100%)',
    accentColor: '#94a3b8',
    parameters: [
      {
        id: 'threshold',
        name: 'THRESHOLD',
        min: -75,
        max: -20,
        step: 1,
        defaultValue: -50,
        unit: ' dB',
        formatValue: (v) => `${v.toFixed(0)} dB`,
      },
      {
        id: 'release',
        name: 'RELEASE',
        min: 0.01,
        max: 0.3,
        step: 0.01,
        defaultValue: 0.05,
        unit: 's',
        formatValue: (v) => `${Math.round(v * 1000)}ms`,
      },
    ],
  },
  compressor: {
    type: 'compressor',
    name: 'DYNAPRESS',
    subtitle: 'Studio Optical Compressor',
    category: 'dynamics',
    chassisColor: 'linear-gradient(180deg, #5c1d24 0%, #2f0e12 100%)',
    accentColor: '#f87171',
    parameters: [
      {
        id: 'threshold',
        name: 'THRESHOLD',
        min: -50,
        max: 0,
        step: 1,
        defaultValue: -20,
        unit: ' dB',
        formatValue: (v) => `${v.toFixed(0)} dB`,
      },
      {
        id: 'ratio',
        name: 'RATIO',
        min: 1,
        max: 20,
        step: 0.5,
        defaultValue: 4,
        formatValue: (v) => `${v.toFixed(1)}:1`,
      },
      {
        id: 'attack',
        name: 'ATTACK',
        min: 0.001,
        max: 0.1,
        step: 0.002,
        defaultValue: 0.015,
        formatValue: (v) => `${Math.round(v * 1000)}ms`,
      },
      {
        id: 'release',
        name: 'RELEASE',
        min: 0.05,
        max: 0.8,
        step: 0.02,
        defaultValue: 0.15,
        formatValue: (v) => `${Math.round(v * 1000)}ms`,
      },
      {
        id: 'makeup',
        name: 'MAKEUP',
        min: 0,
        max: 18,
        step: 0.5,
        defaultValue: 4,
        unit: ' dB',
        formatValue: (v) => `+${v.toFixed(1)} dB`,
      },
    ],
  },
  gain: {
    type: 'gain',
    name: 'BOOSTER PRO',
    subtitle: 'High Headroom Clean Gain',
    category: 'utility',
    chassisColor: 'linear-gradient(180deg, #5c471c 0%, #30240d 100%)',
    accentColor: '#fbbf24',
    parameters: [
      {
        id: 'boost',
        name: 'BOOST',
        min: 0,
        max: 24,
        step: 0.5,
        defaultValue: 6,
        unit: ' dB',
        formatValue: (v) => `+${v.toFixed(1)} dB`,
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  overdrive: {
    type: 'overdrive',
    name: 'TUBE SCREAMER',
    subtitle: 'Warm Asymmetric Tube Drive',
    category: 'drive',
    chassisColor: 'linear-gradient(180deg, #1c4d29 0%, #0c2b15 100%)',
    accentColor: '#4ade80',
    parameters: [
      {
        id: 'drive',
        name: 'OVERDRIVE',
        min: 1,
        max: 30,
        step: 0.5,
        defaultValue: 12,
        formatValue: (v) => v.toFixed(1),
      },
      {
        id: 'tone',
        name: 'TONE',
        min: 1000,
        max: 6500,
        step: 50,
        defaultValue: 3200,
        unit: ' Hz',
        formatValue: (v) => `${(v / 1000).toFixed(1)}k`,
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  distortion: {
    type: 'distortion',
    name: 'IRON RAT',
    subtitle: 'Hard Diode Heavy Distortion',
    category: 'drive',
    chassisColor: 'linear-gradient(180deg, #2d2e33 0%, #16171a 100%)',
    accentColor: '#fb923c',
    parameters: [
      {
        id: 'distortion',
        name: 'DISTORTION',
        min: 1,
        max: 50,
        step: 0.5,
        defaultValue: 18,
        formatValue: (v) => v.toFixed(1),
      },
      {
        id: 'filter',
        name: 'FILTER',
        min: 800,
        max: 8000,
        step: 50,
        defaultValue: 2800,
        unit: ' Hz',
        formatValue: (v) => `${(v / 1000).toFixed(1)}k`,
      },
      {
        id: 'level',
        name: 'VOLUME',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  fuzz: {
    type: 'fuzz',
    name: 'PURPLE HAZE',
    subtitle: 'Vintage Silicon Square Fuzz',
    category: 'drive',
    chassisColor: 'linear-gradient(180deg, #4f225e 0%, #290e32 100%)',
    accentColor: '#c084fc',
    parameters: [
      {
        id: 'fuzz',
        name: 'FUZZ',
        min: 1,
        max: 40,
        step: 0.5,
        defaultValue: 20,
        formatValue: (v) => v.toFixed(1),
      },
      {
        id: 'tone',
        name: 'TONE',
        min: 1200,
        max: 7000,
        step: 50,
        defaultValue: 3000,
        unit: ' Hz',
        formatValue: (v) => `${(v / 1000).toFixed(1)}k`,
      },
      {
        id: 'level',
        name: 'OUTPUT',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  amp: {
    type: 'amp',
    name: 'LEGEND 100',
    subtitle: '12AX7 Tube Preamp & Tone Stack',
    category: 'dynamics',
    chassisColor: 'linear-gradient(180deg, #452c17 0%, #241509 100%)',
    accentColor: '#eab308',
    parameters: [
      {
        id: 'gain',
        name: 'GAIN',
        min: 1,
        max: 20,
        step: 0.5,
        defaultValue: 8,
        formatValue: (v) => v.toFixed(1),
      },
      {
        id: 'bass',
        name: 'BASS',
        min: -12,
        max: 12,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'middle',
        name: 'MID',
        min: -12,
        max: 12,
        step: 0.5,
        defaultValue: 2,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'treble',
        name: 'TREBLE',
        min: -12,
        max: 12,
        step: 0.5,
        defaultValue: 1,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'presence',
        name: 'PRESENCE',
        min: -12,
        max: 12,
        step: 0.5,
        defaultValue: 2,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'master',
        name: 'MASTER',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  cab: {
    type: 'cab',
    name: 'CABINET 4X12',
    subtitle: 'Speaker Impulse Response',
    category: 'dynamics',
    chassisColor: 'linear-gradient(180deg, #243547 0%, #101a26 100%)',
    accentColor: '#60a5fa',
    parameters: [
      {
        id: 'model',
        name: 'SPEAKER',
        min: 0,
        max: 3,
        step: 1,
        defaultValue: 0,
        formatValue: (v) => (v === 0 ? '4x12 V30' : v === 1 ? '2x12 US' : v === 2 ? '1x12 Tweed' : 'Custom IR'),
      },
      {
        id: 'mic',
        name: 'MIC POS',
        min: 0,
        max: 1,
        step: 0.1,
        defaultValue: 0.3,
        formatValue: (v) => (v <= 0.2 ? 'Center' : v >= 0.8 ? 'Edge' : 'Cap-Edge'),
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  chorus: {
    type: 'chorus',
    name: 'OCEAN CHORUS',
    subtitle: 'Lush Analog Modulation',
    category: 'modulation',
    chassisColor: 'linear-gradient(180deg, #184c5c 0%, #0c2730 100%)',
    accentColor: '#38bdf8',
    parameters: [
      {
        id: 'rate',
        name: 'RATE',
        min: 0.2,
        max: 5.0,
        step: 0.1,
        defaultValue: 1.2,
        unit: ' Hz',
        formatValue: (v) => `${v.toFixed(1)} Hz`,
      },
      {
        id: 'depth',
        name: 'DEPTH',
        min: 0.001,
        max: 0.006,
        step: 0.0002,
        defaultValue: 0.003,
        formatValue: (v) => `${(v * 1000).toFixed(1)}ms`,
      },
      {
        id: 'mix',
        name: 'MIX',
        min: 0,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.5,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  tremolo: {
    type: 'tremolo',
    name: 'PULSE TREMOLO',
    subtitle: 'Optical Vintage Tube Pulse',
    category: 'modulation',
    chassisColor: 'linear-gradient(180deg, #59421b 0%, #2e210b 100%)',
    accentColor: '#facc15',
    parameters: [
      {
        id: 'rate',
        name: 'SPEED',
        min: 0.5,
        max: 12.0,
        step: 0.2,
        defaultValue: 4.0,
        unit: ' Hz',
        formatValue: (v) => `${v.toFixed(1)} Hz`,
      },
      {
        id: 'depth',
        name: 'INTENSITY',
        min: 0,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.65,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'level',
        name: 'VOLUME',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  phaser: {
    type: 'phaser',
    name: 'PHASE 90',
    subtitle: '4-Stage Sweeping Phaser',
    category: 'modulation',
    chassisColor: 'linear-gradient(180deg, #6b3314 0%, #361908 100%)',
    accentColor: '#fb923c',
    parameters: [
      {
        id: 'speed',
        name: 'SPEED',
        min: 0.1,
        max: 6.0,
        step: 0.1,
        defaultValue: 0.8,
        unit: ' Hz',
        formatValue: (v) => `${v.toFixed(1)} Hz`,
      },
      {
        id: 'depth',
        name: 'SWEEP',
        min: 200,
        max: 1200,
        step: 25,
        defaultValue: 700,
        unit: ' Hz',
        formatValue: (v) => `${Math.round(v)}`,
      },
      {
        id: 'feedback',
        name: 'RESONANCE',
        min: 0,
        max: 0.7,
        step: 0.05,
        defaultValue: 0.3,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  flanger: {
    type: 'flanger',
    name: 'JET FLANGER',
    subtitle: 'Regenerative Comb Filter',
    category: 'modulation',
    chassisColor: 'linear-gradient(180deg, #541d4c 0%, #2b0c26 100%)',
    accentColor: '#f472b6',
    parameters: [
      {
        id: 'rate',
        name: 'SPEED',
        min: 0.1,
        max: 4.0,
        step: 0.1,
        defaultValue: 0.5,
        unit: ' Hz',
        formatValue: (v) => `${v.toFixed(1)} Hz`,
      },
      {
        id: 'depth',
        name: 'DEPTH',
        min: 0.0005,
        max: 0.003,
        step: 0.0001,
        defaultValue: 0.0018,
        formatValue: (v) => `${(v * 1000).toFixed(1)}ms`,
      },
      {
        id: 'feedback',
        name: 'REGEN',
        min: 0,
        max: 0.85,
        step: 0.05,
        defaultValue: 0.6,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'level',
        name: 'LEVEL',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  delay: {
    type: 'delay',
    name: 'TAPE ECHO',
    subtitle: 'Warm Analog Tape Delay',
    category: 'time',
    chassisColor: 'linear-gradient(180deg, #1d4f52 0%, #0d2829 100%)',
    accentColor: '#2dd4bf',
    parameters: [
      {
        id: 'time',
        name: 'TIME',
        min: 0.05,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.35,
        unit: 's',
        formatValue: (v) => `${Math.round(v * 1000)}ms`,
      },
      {
        id: 'feedback',
        name: 'REPEATS',
        min: 0,
        max: 0.9,
        step: 0.02,
        defaultValue: 0.45,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'tone',
        name: 'TAPE CUT',
        min: 1000,
        max: 7500,
        step: 100,
        defaultValue: 3500,
        unit: ' Hz',
        formatValue: (v) => `${(v / 1000).toFixed(1)}k`,
      },
      {
        id: 'mix',
        name: 'MIX',
        min: 0,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.4,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
    ],
  },
  reverb: {
    type: 'reverb',
    name: 'CELESTIAL REVERB',
    subtitle: 'Diffuse Ambient Space',
    category: 'time',
    chassisColor: 'linear-gradient(180deg, #183861 0%, #0b1c33 100%)',
    accentColor: '#818cf8',
    parameters: [
      {
        id: 'decay',
        name: 'DECAY',
        min: 0.5,
        max: 5.5,
        step: 0.1,
        defaultValue: 2.4,
        unit: 's',
        formatValue: (v) => `${v.toFixed(1)}s`,
      },
      {
        id: 'damp',
        name: 'DAMPING',
        min: 1500,
        max: 8000,
        step: 100,
        defaultValue: 4500,
        unit: ' Hz',
        formatValue: (v) => `${(v / 1000).toFixed(1)}k`,
      },
      {
        id: 'mix',
        name: 'MIX',
        min: 0,
        max: 1.0,
        step: 0.05,
        defaultValue: 0.35,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'level',
        name: 'OUTPUT',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  eq: {
    type: 'eq',
    name: 'TONE SCULPTOR',
    subtitle: '3-Band Studio Equalizer',
    category: 'eq',
    chassisColor: 'linear-gradient(180deg, #3d3023 0%, #1f1811 100%)',
    accentColor: '#d97706',
    parameters: [
      {
        id: 'bass',
        name: 'BASS (100Hz)',
        min: -15,
        max: 15,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'middle',
        name: 'MID (800Hz)',
        min: -15,
        max: 15,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'treble',
        name: 'TREBLE (3.5k)',
        min: -15,
        max: 15,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
      {
        id: 'level',
        name: 'OUTPUT',
        min: -12,
        max: 6,
        step: 0.5,
        defaultValue: 0,
        unit: ' dB',
        formatValue: (v) => `${v >= 0 ? '+' : ''}${v.toFixed(1)} dB`,
      },
    ],
  },
  looper: {
    type: 'looper',
    name: 'LOOP STATION PRO',
    subtitle: 'Infinite Multi-Layer Looper',
    category: 'utility',
    chassisColor: 'linear-gradient(180deg, #4f171e 0%, #27090e 100%)',
    accentColor: '#ef4444',
    parameters: [
      {
        id: 'level',
        name: 'LOOP LEVEL',
        min: 0,
        max: 1.5,
        step: 0.05,
        defaultValue: 1.0,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'feedback',
        name: 'OVERDUB MIX',
        min: 0.2,
        max: 1.0,
        step: 0.02,
        defaultValue: 1.0,
        formatValue: (v) => `${Math.round(v * 100)}%`,
      },
      {
        id: 'speed',
        name: 'SPEED',
        min: 0.5,
        max: 2.0,
        step: 0.5,
        defaultValue: 1.0,
        formatValue: (v) => `${v}x`,
      },
      {
        id: 'reverse',
        name: 'REVERSE',
        min: 0,
        max: 1,
        step: 1,
        defaultValue: 0,
        formatValue: (v) => (v > 0.5 ? 'REV' : 'FWD'),
      },
    ],
  },
};

export function createPedalAudioNode(
  type: string,
  ctx: AudioContext,
  id: string,
  initialParams?: Record<string, number>,
  enabled = true
): AudioPedalNode {
  switch (type) {
    case 'noiseGate':
      return new NoiseGatePedalNode(ctx, id, initialParams, enabled);
    case 'compressor':
      return new CompressorPedalNode(ctx, id, initialParams, enabled);
    case 'gain':
      return new GainPedalNode(ctx, id, initialParams, enabled);
    case 'overdrive':
      return new OverdrivePedalNode(ctx, id, initialParams, enabled);
    case 'distortion':
      return new DistortionPedalNode(ctx, id, initialParams, enabled);
    case 'fuzz':
      return new FuzzPedalNode(ctx, id, initialParams, enabled);
    case 'amp':
      return new AmpPedalNode(ctx, id, initialParams, enabled);
    case 'cab':
      return new CabPedalNode(ctx, id, initialParams, enabled);
    case 'chorus':
      return new ChorusPedalNode(ctx, id, initialParams, enabled);
    case 'tremolo':
      return new TremoloPedalNode(ctx, id, initialParams, enabled);
    case 'phaser':
      return new PhaserPedalNode(ctx, id, initialParams, enabled);
    case 'flanger':
      return new FlangerPedalNode(ctx, id, initialParams, enabled);
    case 'delay':
      return new DelayPedalNode(ctx, id, initialParams, enabled);
    case 'reverb':
      return new ReverbPedalNode(ctx, id, initialParams, enabled);
    case 'eq':
      return new Eq3BandPedalNode(ctx, id, initialParams, enabled);
    case 'looper':
      return new LooperPedalNode(ctx, id, initialParams, enabled);
    default:
      throw new Error(`Unknown pedal type: ${type}`);
  }
}
